networks:
  traefik_network:
    name: traefik_network
secrets:
  auth_users:
    file: ./secret/auth_users.txt
services:
  traefik:
    image: traefik:${TRAEFIK_IMAGE_VERSION:-latest}
    command:
      - --api.dashboard=${TRAEFIK_ENABLE_DASHBOARD:-false}

      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls=true
      - --entrypoints.https.http.tls.certresolver=letsencrypt

      - --entrypoints.https.http.tls.domains[0].main=${TRAEFIK_ROOT_FULLY_QUALIFIED_DOMAIN_NAME}
      - --entrypoints.https.http.tls.domains[0].sans=*.${TRAEFIK_ROOT_FULLY_QUALIFIED_DOMAIN_NAME}

      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=${TRAEFIK_ACME_DNS_PROVIDER}
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delayBeforeCheck=30
    restart: unless-stopped
    env_file:
      - dns-challenge.env
      - .env
    networks:
      - traefik_network
    ports:
      - 80:80
      - 443:443
    secrets:
      - auth_users
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_network

      - traefik.http.middlewares.basic-auth.basicauth.usersFile=/run/secrets/auth_users

      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_FULLY_QUALIFIED_DOMAIN_NAME}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=basic-auth
  app:
    image: ghcr.io/luma2010/heig-vd-dai-projet-pratique3:latest
    networks:
      - traefik_network
    restart: unless-stopped
    container_name: mon_app
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_network

      - traefik.http.routers.mon_app.entrypoints=https
      - traefik.http.routers.mon_app.rule=Host(`app.${TRAEFIK_ROOT_FULLY_QUALIFIED_DOMAIN_NAME}`)
      - traefik.http.services.mon_app.loadbalancer.server.port=5000 # Port exposé par ton application

